
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 02 01:18:31 CEST 2012
//----------------------------------------------------

package compiler.synanal;

/** CUP generated class containing symbol constants. */
public class PascalTok {
  /* terminals */
  public static final int CHAR_CONST = 3;
  public static final int VAL = 36;
  public static final int LTH = 26;
  public static final int FUNCTION = 45;
  public static final int LBRACKET = 14;
  public static final int CONST = 40;
  public static final int CHAR = 8;
  public static final int SEMIC = 18;
  public static final int INT = 9;
  public static final int ARRAY = 37;
  public static final int FOR = 44;
  public static final int NOT = 30;
  public static final int AND = 20;
  public static final int RECORD = 50;
  public static final int TYPE = 53;
  public static final int NIL = 5;
  public static final int OR = 31;
  public static final int BOOL = 7;
  public static final int COMMA = 11;
  public static final int BEGIN = 39;
  public static final int DIV = 21;
  public static final int GEQ = 23;
  public static final int IF = 46;
  public static final int ASSIGN = 38;
  public static final int DOT = 12;
  public static final int UADD = 34;
  public static final int PTR = 32;
  public static final int OF = 47;
  public static final int DOTS = 13;
  public static final int EOF = 0;
  public static final int RBRACKET = 16;
  public static final int INT_CONST = 4;
  public static final int PROGRAM = 49;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int ADD = 19;
  public static final int LPARENTHESIS = 15;
  public static final int NEQ = 29;
  public static final int GTH = 24;
  public static final int EQU = 22;
  public static final int COLON = 10;
  public static final int ELSE = 42;
  public static final int TO = 52;
  public static final int MEM = 27;
  public static final int WHILE = 55;
  public static final int THEN = 51;
  public static final int RPARENTHESIS = 17;
  public static final int LEQ = 25;
  public static final int END = 43;
  public static final int USUB = 35;
  public static final int BOOL_CONST = 2;
  public static final int SUB = 33;
  public static final int VAR = 54;
  public static final int PROCEDURE = 48;
  public static final int DO = 41;
  public static final int IDENTIFIER = 6;

  /* non terminals */
  static final int const_list = 5;
  static final int procedure_name = 15;
  static final int single_var = 12;
  static final int unary_postfix_expression = 41;
  static final int function_name = 17;
  static final int declarations_type = 7;
  static final int no_if_statement = 48;
  static final int add_sub_expression = 37;
  static final int declarations_const = 4;
  static final int or_expression = 34;
  static final int record_components = 29;
  static final int declarations_subrutine = 13;
  static final int single_const = 6;
  static final int subrutine_function = 16;
  static final int matched_if_statement = 47;
  static final int single_record_component = 30;
  static final int single_type = 9;
  static final int statement_block = 43;
  static final int type_record = 28;
  static final int unmatched_if_statement = 46;
  static final int unary_prefix_expression = 40;
  static final int source = 0;
  static final int type_description = 24;
  static final int type_pointer = 31;
  static final int statement = 45;
  static final int not_expression = 39;
  static final int parameter_discription_list = 19;
  static final int primitive_type = 25;
  static final int declarations_var = 10;
  static final int and_expression = 35;
  static final int reference_type = 26;
  static final int parameter_declaration = 18;
  static final int parameter_list = 22;
  static final int type_list = 8;
  static final int input_parameters = 21;
  static final int var_list = 11;
  static final int while_statement = 49;
  static final int program_name = 1;
  static final int type_array = 27;
  static final int single_parameter = 23;
  static final int source_body = 2;
  static final int single_parameter_discription = 20;
  static final int declarations = 3;
  static final int value_expression = 32;
  static final int subrutine_procedure = 14;
  static final int mul_div_expression = 38;
  static final int relation_expression = 36;
  static final int const_values = 33;
  static final int values = 42;
  static final int statement_list = 44;
}

