
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 01 15:42:40 CEST 2012
//----------------------------------------------------

package compiler.synanal;

/** CUP generated class containing symbol constants. */
public class PascalTok {
  /* terminals */
  public static final int CHAR_CONST = 3;
  public static final int VAL = 36;
  public static final int LTH = 26;
  public static final int FUNCTION = 45;
  public static final int LBRACKET = 14;
  public static final int CONST = 40;
  public static final int CHAR = 8;
  public static final int SEMIC = 18;
  public static final int INT = 9;
  public static final int ARRAY = 37;
  public static final int FOR = 44;
  public static final int NOT = 30;
  public static final int AND = 20;
  public static final int RECORD = 50;
  public static final int TYPE = 53;
  public static final int NIL = 5;
  public static final int OR = 31;
  public static final int BOOL = 7;
  public static final int COMMA = 11;
  public static final int BEGIN = 39;
  public static final int DIV = 21;
  public static final int GEQ = 23;
  public static final int IF = 46;
  public static final int ASSIGN = 38;
  public static final int DOT = 12;
  public static final int UADD = 34;
  public static final int PTR = 32;
  public static final int OF = 47;
  public static final int DOTS = 13;
  public static final int EOF = 0;
  public static final int RBRACKET = 16;
  public static final int INT_CONST = 4;
  public static final int PROGRAM = 49;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int ADD = 19;
  public static final int LPARENTHESIS = 15;
  public static final int NEQ = 29;
  public static final int GTH = 24;
  public static final int EQU = 22;
  public static final int COLON = 10;
  public static final int ELSE = 42;
  public static final int TO = 52;
  public static final int MEM = 27;
  public static final int WHILE = 55;
  public static final int THEN = 51;
  public static final int RPARENTHESIS = 17;
  public static final int LEQ = 25;
  public static final int END = 43;
  public static final int USUB = 35;
  public static final int BOOL_CONST = 2;
  public static final int SUB = 33;
  public static final int VAR = 54;
  public static final int PROCEDURE = 48;
  public static final int DO = 41;
  public static final int IDENTIFIER = 6;

  /* non terminals */
  static final int const_values = 31;
  static final int type_record = 26;
  static final int subrutine_procedure = 14;
  static final int declarations_subrutine = 13;
  static final int record_components = 27;
  static final int declarations_var = 10;
  static final int single_record_component = 28;
  static final int var_list = 11;
  static final int program_name = 2;
  static final int declarations_type = 7;
  static final int single_var = 12;
  static final int binary_expression = 32;
  static final int function_name = 17;
  static final int subrutine_function = 16;
  static final int type_array = 25;
  static final int single_type = 9;
  static final int type_pointer = 29;
  static final int reference_type = 24;
  static final int statement_block = 18;
  static final int procedure_name = 15;
  static final int value_expression = 30;
  static final int primitive_type = 23;
  static final int single_const = 6;
  static final int const_list = 5;
  static final int declarations = 3;
  static final int source = 0;
  static final int source_body = 1;
  static final int parameter_list = 20;
  static final int type_list = 8;
  static final int parameter_declaration = 19;
  static final int type_description = 22;
  static final int single_parameter = 21;
  static final int declarations_const = 4;
}

